USER_OPT="--disable-everything
"
PROT_OPT_MOBILE="--enable-protocol=cache,concat*,*content,crypto*,data,fd,*file,ftp,h*,i*,pipe,rt*,s*,t*,u*"
PROT_OPT="${PROT_OPT_MOBILE}"
DEMUX_OPT="--enable-demuxer=mov"
MUX_OPT="--enable-muxer=mp4"
android_OPT="--disable-avdevice"
ios_OPT="--disable-avdevice"
rpi_OPT="--disable-avdevice"
raspberry_pi_OPT="--disable-avdevice"
sunxi_OPT="--disable-avdevice"
LITE_BUILD=true